os: osx
osx_image: xcode10.2
language: objective-c
sudo: false
env:
  global:
  - THEOS=~/theos
before_install:
  - brew update
  - brew install dpkg ldid
  - git clone --recursive git://github.com/theos/theos.git ~/theos
script:
  - "export VERSION=$(grep 'Version: ' control | sed 's/^.*: //')"
  - "export DESCRIPTION=$(awk '/## v$VERSION/{getline; print}' README.md)"
  - "export FILENAME='packages/'\"$(grep 'Package: ' control | sed 's/^.*: //')\"'_'\"$VERSION\"'_iphoneos-arm.deb'"
  - make package
before_deploy:
  - git config --local user.name "Jeff Rescignano"
  - git config --local user.email "jeff@jeffresc.com"
  - git tag -a v$VERSION -m "$DESCRIPTION"
deploy:
  provider: releases
  api_key:
    secure: CXFE+6YanWm3SPZSuTWKgAoNA0GTf8O4bJSshhzwxmgi+3wGTmsvlhf7Hhie9h/c89opiiuifYG17xY/beasjF6TPXeS32ti2/flDYiYetosG+zi6v73K78uNnnJvGzjCXz70/E/6G8OVB/1W3+xP/Odl6sI8o7Zdm+eBtPeqMuEUY/2yP4GNKW3EdtIQtNsitjT+8f9UKONMbIiUHxTidbriUm2AAEYheTwVZQolqs6sRecfxIu85YRt0Vcl53z/xNHTkAzQpO2/KApEDQgk4lsL6ePtwmQ7Xf8Tu6/fsZuZE5VRV569ek7YltufQnlTTzsQwSz6E7YACi2j4sPQSN9kul+i/OQHPnbuRZyPP6WVq/lFEaJVItwnx6WADUaMV+PVPaZzcBO4zMN3+Y0iX9jd44yFRR8PzAKmtn8QKAvI1CLkOGYDoLPrbjahcrvEikh27NUwRrOb29JjQig8svADeilr4ZCir6cqhxPC+p1Rg/pa14dDgWlijfQ2FvnV6dI7PzoArF5ymQf2XPaEuG/nICgVRGiKv6k0tbMTMXtKc627NjNBEvBwTTcreJnhwf4+FUd7UsbixBk2M0/26WOXA4W1tXw0ZRWhxzFv5GHvlXp+CT+5gIi/4pymxyuTPXiszpRFVbjYz8gbEO1Z9GqQyibhu/eOtkLno/3TpU=
  file: $FILENAME
  skip_cleanup: true
  on:
    branches:
      only:
        - master
branches:
  except:
  - /^untagged/
